bch-y = \
	../../third_party/nuttx/drivers/bch/bchlib_setup.o \
	../../third_party/nuttx/drivers/bch/bchlib_teardown.o \
	../../third_party/nuttx/drivers/bch/bchlib_read.o \
	../../third_party/nuttx/drivers/bch/bchlib_write.o \
	../../third_party/nuttx/drivers/bch/bchlib_cache.o \
	../../third_party/nuttx/drivers/bch/bchlib_sem.o \
	../../third_party/nuttx/drivers/bch/bchdev_register.o \
	../../third_party/nuttx/drivers/bch/bchdev_unregister.o \
	../../third_party/nuttx/drivers/bch/bchdev_driver.o

obj-y += bch.o
