saradc-$(CONFIG_CMDS_ADC_TEST) += adc_test_menu.o
saradc-$(CONFIG_CMDS_TOUCH_ADC_TEST) += touch_adc_test.o
saradc-$(CONFIG_CMDS_KEY_ADC_TEST) += key_adc_test.o
saradc-$(CONFIG_CMDS_QUERY_ADC_TEST) += query_adc_test.o 
obj-y += saradc.o
