# os/linux_netlink.o 
# os/linux_usbfs.o 
# os/threads_posix.o 

libusb-y := descriptor.o \
			io.o \
			hotplug.o \
			strerror.o \
			core.o \
			sync.o \
			os/events_posix.o \
			os/threads_posix.o \
			os/hcrtos_usbfs.o \
			os/hcrtos_hotplug.o 
obj-y += libusb.o
