libc-y = \
	callocr.o 	\
	environ.o 	\
	execve.o 	\
	exit.o 		\
	fork.o 		\
	freer.o 	\
	getpid.o 	\
	gettimeofday.o 	\
	_platform_time.o\
	settimeofday.o 	\
	isatty.o 	\
	kill.o 		\
	mallocr.o 	\
	reallocr.o 	\
	times.o 	\
	wait.o 		\
	sleep.o		\
	msleep.o	\
	ffs.o		\
	getchar.o	\
	hostname.o	\
	abort.o		\
	putchar.o	\
	usleep.o	\
	delay.o		\
	basename.o	\
	clock_settime.o \
	clock_gettime.o \
	alloc.o		\
	errno.o		\
	fesetround.o	\
	getentropy.o	\
	../../third_party/nuttx/libs/libc/unistd/lib_chdir.o	\
	../../third_party/nuttx/libs/libc/unistd/lib_getcwd.o	\
	../../third_party/nuttx/libs/libc/libgen/lib_dirname.o	\
	../../third_party/nuttx/libs/libc/unistd/lib_pipe2.o	\
	../../third_party/nuttx/libs/libc/unistd/lib_pipe.o	\
	../../third_party/nuttx/libs/libc/unistd/lib_access.o	\
	../../third_party/nuttx/libs/libc/misc/lib_fnmatch.o


obj-y += libc.o

