#ifndef _HC15XX_PINMUX_H_
#define _HC15XX_PINMUX_H_

#ifdef __cplusplus
extern "C" {
#endif

#define PINMUX_FUNCTION_SEL0 0
#define PINMUX_FUNCTION_SEL1 1
#define PINMUX_FUNCTION_SEL2 2
#define PINMUX_FUNCTION_SEL3 3
#define PINMUX_FUNCTION_SEL4 4
#define PINMUX_FUNCTION_SEL5 5
#define PINMUX_FUNCTION_SEL6 6
#define PINMUX_FUNCTION_SEL7 7
#define PINMUX_FUNCTION_SEL8 8
#define PINMUX_FUNCTION_SEL9 9
#define PINMUX_FUNCTION_SELA 10
#define PINMUX_FUNCTION_SELB 11

#define PINMUX_L00_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L00_PRGB_B1				PINMUX_FUNCTION_SEL6
#define PINMUX_L00_I2C3_SCL				PINMUX_FUNCTION_SEL8

#define PINMUX_L01_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L01_PRGB_B2				PINMUX_FUNCTION_SEL6

#define PINMUX_L02_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L02_PRGB_B3				PINMUX_FUNCTION_SEL6

#define PINMUX_L03_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L03_PRGB_B4				PINMUX_FUNCTION_SEL6

#define PINMUX_L04_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L04_PRGB_B5				PINMUX_FUNCTION_SEL6

#define PINMUX_L05_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L05_PRGB_B6				PINMUX_FUNCTION_SEL6

#define PINMUX_L06_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L06_PRGB_B7				PINMUX_FUNCTION_SEL6

#define PINMUX_L07_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L07_PRGB_CLK				PINMUX_FUNCTION_SEL6

#define PINMUX_L08_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L08_PRGB_HSYN				PINMUX_FUNCTION_SEL6

#define PINMUX_L09_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L09_PRGB_VSYNC				PINMUX_FUNCTION_SEL6

#define PINMUX_L10_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L10_PWN_0				PINMUX_FUNCTION_SEL1
#define PINMUX_L10_IR					PINMUX_FUNCTION_SEL3
#define PINMUX_L10_PRGB_DE				PINMUX_FUNCTION_SEL6

#define PINMUX_L11_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L11_SF_CSJ_0				PINMUX_FUNCTION_SEL1

#define PINMUX_L12_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L12_SF_MISO				PINMUX_FUNCTION_SEL1

#define PINMUX_L13_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L13_SF_MOSI				PINMUX_FUNCTION_SEL1

#define PINMUX_L14_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L14_SF_CLK				PINMUX_FUNCTION_SEL1

#define PINMUX_L15_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L15_SF_CSJ_1				PINMUX_FUNCTION_SEL1
#define PINMUX_L15_F_CRYSTAL				PINMUX_FUNCTION_SEL7

#define PINMUX_L16_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L16_SSI_MISTART				PINMUX_FUNCTION_SEL1
#define PINMUX_L16_SDIO_D1				PINMUX_FUNCTION_SEL4
#define PINMUX_L16_VIN_D0				PINMUX_FUNCTION_SEL5
#define PINMUX_L16_VIN_D7				PINMUX_FUNCTION_SEL6
#define PINMUX_L16_UART0_RX				PINMUX_FUNCTION_SEL7

#define PINMUX_L17_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L17_SSI_MIVALA				PINMUX_FUNCTION_SEL1
#define PINMUX_L17_SDIO_D0				PINMUX_FUNCTION_SEL4
#define PINMUX_L17_VIN_D1				PINMUX_FUNCTION_SEL5
#define PINMUX_L17_VIN_D6				PINMUX_FUNCTION_SEL6
#define PINMUX_L17_UART0_TX				PINMUX_FUNCTION_SEL7

#define PINMUX_L18_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L18_SSI_MICLK				PINMUX_FUNCTION_SEL1
#define PINMUX_L18_SDIO_CLK				PINMUX_FUNCTION_SEL4
#define PINMUX_L18_VIN_D2				PINMUX_FUNCTION_SEL5
#define PINMUX_L18_VIN_D5				PINMUX_FUNCTION_SEL6

#define PINMUX_L19_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L19_SSI_MDI_0				PINMUX_FUNCTION_SEL1
#define PINMUX_L19_SDIO_CMD				PINMUX_FUNCTION_SEL4
#define PINMUX_L19_VIN_D3				PINMUX_FUNCTION_SEL5
#define PINMUX_L19_VIN_D4				PINMUX_FUNCTION_SEL6

#define PINMUX_L20_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L20_I2C0_SDA				PINMUX_FUNCTION_SEL3
#define PINMUX_L20_SDIO_D3				PINMUX_FUNCTION_SEL4
#define PINMUX_L20_VIN_D4				PINMUX_FUNCTION_SEL5
#define PINMUX_L20_VIN_D3				PINMUX_FUNCTION_SEL6

#define PINMUX_L21_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L21_I2C0_SCL				PINMUX_FUNCTION_SEL3
#define PINMUX_L21_SDIO_D2				PINMUX_FUNCTION_SEL4
#define PINMUX_L21_VIN_D5				PINMUX_FUNCTION_SEL5
#define PINMUX_L21_VIN_D2				PINMUX_FUNCTION_SEL6

#define PINMUX_L22_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L22_PWM_0				PINMUX_FUNCTION_SEL1
#define PINMUX_L22_I2S_BCLK				PINMUX_FUNCTION_SEL2
#define PINMUX_L22_IR					PINMUX_FUNCTION_SEL3
#define PINMUX_L22_SPDIF				PINMUX_FUNCTION_SEL4
#define PINMUX_L22_VIN_CLK				PINMUX_FUNCTION_SEL5
#define PINMUX_L22_CRYSTAL				PINMUX_FUNCTION_SEL7

#define PINMUX_L23_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L23_PWM_0				PINMUX_FUNCTION_SEL1
#define PINMUX_L23_I2S_DATAI				PINMUX_FUNCTION_SEL2
#define PINMUX_L23_I2S_DATAO				PINMUX_FUNCTION_SEL3
#define PINMUX_L23_IR					PINMUX_FUNCTION_SEL4
#define PINMUX_L23_VIN_D6				PINMUX_FUNCTION_SEL5
#define PINMUX_L23_VIN_D1				PINMUX_FUNCTION_SEL6

#define PINMUX_L24_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L24_SSI_MISTART				PINMUX_FUNCTION_SEL1
#define PINMUX_L24_I2S_LRCK				PINMUX_FUNCTION_SEL2
#define PINMUX_L24_I2S_MCLK				PINMUX_FUNCTION_SEL3
#define PINMUX_L24_HDMI_TX_CLK_EXT			PINMUX_FUNCTION_SEL4
#define PINMUX_L24_VIN_D7				PINMUX_FUNCTION_SEL5
#define PINMUX_L24_VIN_D0				PINMUX_FUNCTION_SEL6

#define PINMUX_L25_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L25_SSI_MIVALA				PINMUX_FUNCTION_SEL1
#define PINMUX_L25_I2S_BCLK				PINMUX_FUNCTION_SEL2
#define PINMUX_L25_SPDIF				PINMUX_FUNCTION_SEL4
#define PINMUX_L25_HDMI_TMDS_CLK_EXT			PINMUX_FUNCTION_SEL5
#define PINMUX_L25_VIN_CLK				PINMUX_FUNCTION_SEL6

#define PINMUX_L26_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L26_SSI_MICLK				PINMUX_FUNCTION_SEL1
#define PINMUX_L26_I2S_MCLK				PINMUX_FUNCTION_SEL2
#define PINMUX_L26_I2S_LRCK				PINMUX_FUNCTION_SEL3
#define PINMUX_L26_SPDIF				PINMUX_FUNCTION_SEL4
#define PINMUX_L26_HDMI_CEC				PINMUX_FUNCTION_SEL5
#define PINMUX_L26_TVE_HSYNC				PINMUX_FUNCTION_SEL6
#define PINMUX_L26_VIN_HSYNC				PINMUX_FUNCTION_SEL7

#define PINMUX_L27_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L27_SSI_MDI_0				PINMUX_FUNCTION_SEL1
#define PINMUX_L27_I2S_DATAO				PINMUX_FUNCTION_SEL2
#define PINMUX_L27_I2S_DATAI				PINMUX_FUNCTION_SEL3
#define PINMUX_L27_SPDIF				PINMUX_FUNCTION_SEL4
#define PINMUX_L27_HDMI_HTPG				PINMUX_FUNCTION_SEL5
#define PINMUX_L27_TVE_VSYNC				PINMUX_FUNCTION_SEL6
#define PINMUX_L27_VIN_VSYNC				PINMUX_FUNCTION_SEL7

#define PINMUX_L28_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L28_UART0_RX				PINMUX_FUNCTION_SEL2
#define PINMUX_L28_I2C1_SDA				PINMUX_FUNCTION_SEL3

#define PINMUX_L29_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L29_UART0_TX				PINMUX_FUNCTION_SEL2
#define PINMUX_L29_I2C1_SCL				PINMUX_FUNCTION_SEL3

#define PINMUX_B00_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B00_I2C2_SDA				PINMUX_FUNCTION_SEL3
#define PINMUX_B00_I2S_DATAO				PINMUX_FUNCTION_SEL7

#define PINMUX_B01_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B01_I2C2_SCL				PINMUX_FUNCTION_SEL3
#define PINMUX_B01_I2S_BCLK				PINMUX_FUNCTION_SEL7

#define PINMUX_B02_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B02_PWM_1				PINMUX_FUNCTION_SEL1
#define PINMUX_B02_I2C2_SDA				PINMUX_FUNCTION_SEL3
#define PINMUX_B02_SPDIF				PINMUX_FUNCTION_SEL4
#define PINMUX_B02_PRGB_DE				PINMUX_FUNCTION_SEL5
#define PINMUX_B02_I2S_LRCK				PINMUX_FUNCTION_SEL7

#define PINMUX_B03_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B03_PWM_1				PINMUX_FUNCTION_SEL1
#define PINMUX_B03_I2C2_SCL				PINMUX_FUNCTION_SEL3
#define PINMUX_B03_IR					PINMUX_FUNCTION_SEL4
#define PINMUX_B03_PRGB_R0				PINMUX_FUNCTION_SEL5
#define PINMUX_B03_I2S_DATAI				PINMUX_FUNCTION_SEL7

#define PINMUX_R00_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_R00_SF_CSJ_0				PINMUX_FUNCTION_SEL1
#define PINMUX_R00_PRGB_R0				PINMUX_FUNCTION_SEL5
#define PINMUX_R00_PRGB_DE				PINMUX_FUNCTION_SEL7
#define PINMUX_R00_I2C3_SDA				PINMUX_FUNCTION_SEL8

#define PINMUX_R01_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_R01_SF_MISO				PINMUX_FUNCTION_SEL1
#define PINMUX_R01_PRGB_R1				PINMUX_FUNCTION_SEL5
#define PINMUX_R01_I2C3_SCL				PINMUX_FUNCTION_SEL8

#define PINMUX_R02_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_R02_SF_MOSI				PINMUX_FUNCTION_SEL1
#define PINMUX_R02_PRGB_R2				PINMUX_FUNCTION_SEL5

#define PINMUX_R03_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_R03_SF_CLK				PINMUX_FUNCTION_SEL1
#define PINMUX_R03_PRGB_R3				PINMUX_FUNCTION_SEL5

#define PINMUX_R04_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_R04_SF_SCJ1				PINMUX_FUNCTION_SEL1
#define PINMUX_R04_SDIO_D2				PINMUX_FUNCTION_SEL4
#define PINMUX_R04_PRGB_R4				PINMUX_FUNCTION_SEL5

#define PINMUX_R05_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_R05_PWM_2				PINMUX_FUNCTION_SEL1
#define PINMUX_R05_UART1_RX				PINMUX_FUNCTION_SEL2
#define PINMUX_R05_I2C0_SDA				PINMUX_FUNCTION_SEL3
#define PINMUX_R05_USB_DBG_STATUS_0			PINMUX_FUNCTION_SEL4
#define PINMUX_R05_PRGB_R5				PINMUX_FUNCTION_SEL5

#define PINMUX_R06_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_R06_TVE_HSYNC				PINMUX_FUNCTION_SEL3
#define PINMUX_R06_PRGB_R6				PINMUX_FUNCTION_SEL5

#define PINMUX_R07_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_R07_TVE_VSYNC				PINMUX_FUNCTION_SEL3
#define PINMUX_R07_IR					PINMUX_FUNCTION_SEL5

#define PINMUX_R08_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_R08_UART1_TX				PINMUX_FUNCTION_SEL2
#define PINMUX_R08_I2C2_SCL				PINMUX_FUNCTION_SEL3
#define PINMUX_R08_USB_DBG_STATUS_1			PINMUX_FUNCTION_SEL4
#define PINMUX_R08_PRGB_G0				PINMUX_FUNCTION_SEL5
#define PINMUX_R08_PRGB_R0				PINMUX_FUNCTION_SEL6
#define PINMUX_R08_PRGB_G1				PINMUX_FUNCTION_SEL7

#define PINMUX_T00_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T00_TVE_HSYNC				PINMUX_FUNCTION_SEL3
#define PINMUX_T00_SDIO_D1				PINMUX_FUNCTION_SEL4
#define PINMUX_T00_PRGB_G1				PINMUX_FUNCTION_SEL5
#define PINMUX_T00_PRGB_R1				PINMUX_FUNCTION_SEL6
#define PINMUX_T00_PRGB_G3				PINMUX_FUNCTION_SEL7
#define PINMUX_T00_UART1_RX				PINMUX_FUNCTION_SEL8

#define PINMUX_T01_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T01_TVE_VSYNC				PINMUX_FUNCTION_SEL3
#define PINMUX_T01_SDIO_D0				PINMUX_FUNCTION_SEL4
#define PINMUX_T01_PRGB_G2				PINMUX_FUNCTION_SEL5
#define PINMUX_T01_PRGB_R2				PINMUX_FUNCTION_SEL6
#define PINMUX_T01_PRGB_G0				PINMUX_FUNCTION_SEL7
#define PINMUX_T01_UART1_RX				PINMUX_FUNCTION_SEL8

#define PINMUX_T02_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T02_UART1_RX				PINMUX_FUNCTION_SEL2
#define PINMUX_T02_I2C3_SCL				PINMUX_FUNCTION_SEL3
#define PINMUX_T02_SDIO_CLK				PINMUX_FUNCTION_SEL4
#define PINMUX_T02_PRGB_G3				PINMUX_FUNCTION_SEL5
#define PINMUX_T02_PRGB_R3				PINMUX_FUNCTION_SEL6
#define PINMUX_T02_PRGB_G4				PINMUX_FUNCTION_SEL7

#define PINMUX_T03_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T03_UART1_TX				PINMUX_FUNCTION_SEL2
#define PINMUX_T03_I2C3_SDA				PINMUX_FUNCTION_SEL3
#define PINMUX_T03_SDIO_CMD				PINMUX_FUNCTION_SEL4
#define PINMUX_T03_PRGB_G4				PINMUX_FUNCTION_SEL5
#define PINMUX_T03_PRGB_R4				PINMUX_FUNCTION_SEL6
#define PINMUX_T03_PRGB_G2				PINMUX_FUNCTION_SEL7

#define PINMUX_T04_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T04_SSI_MDI_0				PINMUX_FUNCTION_SEL1
#define PINMUX_T04_SDIO_D3				PINMUX_FUNCTION_SEL4
#define PINMUX_T04_PRGB_G5				PINMUX_FUNCTION_SEL5
#define PINMUX_T04_PRGB_R5				PINMUX_FUNCTION_SEL6
#define PINMUX_T04_PRGB_G6				PINMUX_FUNCTION_SEL7

#define PINMUX_T05_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T05_SSI_MICLK				PINMUX_FUNCTION_SEL1
#define PINMUX_T05_SDIO_D2				PINMUX_FUNCTION_SEL4
#define PINMUX_T05_PRGB_G6				PINMUX_FUNCTION_SEL5
#define PINMUX_T05_PRGB_R6				PINMUX_FUNCTION_SEL6
#define PINMUX_T05_PRGB_G5				PINMUX_FUNCTION_SEL7

#define PINMUX_T06_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T06_SSI_MIVALA				PINMUX_FUNCTION_SEL1
#define PINMUX_T06_I2C2_SCL				PINMUX_FUNCTION_SEL3
#define PINMUX_T06_PRGB_G7				PINMUX_FUNCTION_SEL5
#define PINMUX_T06_PRGB_R7				PINMUX_FUNCTION_SEL6

#define PINMUX_T07_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T07_SSI_MISTART				PINMUX_FUNCTION_SEL1
#define PINMUX_T07_I2C2_SDA				PINMUX_FUNCTION_SEL3
#define PINMUX_T07_PRGB_B0				PINMUX_FUNCTION_SEL5
#define PINMUX_T07_PRGB_G0				PINMUX_FUNCTION_SEL6
#define PINMUX_T07_I2C0_SDA				PINMUX_FUNCTION_SEL8

#define PINMUX_T08_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T08_SSI_MDI_0				PINMUX_FUNCTION_SEL1
#define PINMUX_T08_I2S_DATA1				PINMUX_FUNCTION_SEL2
#define PINMUX_T08_EJ_TRSTJ				PINMUX_FUNCTION_SEL3
#define PINMUX_T08_SDIO_D1				PINMUX_FUNCTION_SEL4
#define PINMUX_T08_PRGB_B1				PINMUX_FUNCTION_SEL5
#define PINMUX_T08_PRGB_G1				PINMUX_FUNCTION_SEL6
#define PINMUX_T08_I2C0_SCL				PINMUX_FUNCTION_SEL8

#define PINMUX_T09_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T09_SSI_MICLK				PINMUX_FUNCTION_SEL1
#define PINMUX_T09_I2S_LRCK				PINMUX_FUNCTION_SEL2
#define PINMUX_T09_EJ_TDI				PINMUX_FUNCTION_SEL3
#define PINMUX_T09_SDIO_D0				PINMUX_FUNCTION_SEL4
#define PINMUX_T09_PRGB_B2				PINMUX_FUNCTION_SEL5
#define PINMUX_T09_PRGB_G2				PINMUX_FUNCTION_SEL6

#define PINMUX_T10_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T10_SSI_MVALA				PINMUX_FUNCTION_SEL1
#define PINMUX_T10_I2S_BCLK				PINMUX_FUNCTION_SEL2
#define PINMUX_T10_EJ_TDO				PINMUX_FUNCTION_SEL3
#define PINMUX_T10_SDIO_CLK				PINMUX_FUNCTION_SEL4
#define PINMUX_T10_PRGB_B3				PINMUX_FUNCTION_SEL5
#define PINMUX_T10_PRGB_G3				PINMUX_FUNCTION_SEL6

#define PINMUX_T11_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T11_SSI_MISTART				PINMUX_FUNCTION_SEL1
#define PINMUX_T11_I2S_MCLK				PINMUX_FUNCTION_SEL2
#define PINMUX_T11_EJ_TMS				PINMUX_FUNCTION_SEL3
#define PINMUX_T11_SDIO_CMD				PINMUX_FUNCTION_SEL4
#define PINMUX_T11_PRGB_B4				PINMUX_FUNCTION_SEL5
#define PINMUX_T11_PRGB_G4				PINMUX_FUNCTION_SEL6

#define PINMUX_T12_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T12_PWM_2				PINMUX_FUNCTION_SEL1
#define PINMUX_T12_I2S_DATAO				PINMUX_FUNCTION_SEL2
#define PINMUX_T12_EJ_TCLK				PINMUX_FUNCTION_SEL3
#define PINMUX_T12_SDIO_D3				PINMUX_FUNCTION_SEL4
#define PINMUX_T12_PRGB_B5				PINMUX_FUNCTION_SEL5
#define PINMUX_T12_PRGB_G5				PINMUX_FUNCTION_SEL6

#define PINMUX_T13_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T13_CPUDIG_PLL_TFCK			PINMUX_FUNCTION_SEL1
#define PINMUX_T13_PRGB_B6				PINMUX_FUNCTION_SEL5
#define PINMUX_T13_PRGB_G6				PINMUX_FUNCTION_SEL6

#define PINMUX_T14_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T14_UART1_RX				PINMUX_FUNCTION_SEL2
#define PINMUX_T14_I2C3_SDA				PINMUX_FUNCTION_SEL3
#define PINMUX_T14_PRGB_B7				PINMUX_FUNCTION_SEL5
#define PINMUX_T14_PRGB_G7				PINMUX_FUNCTION_SEL6

#define PINMUX_T15_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T15_PWM_2				PINMUX_FUNCTION_SEL1
#define PINMUX_T15_UART1_TX				PINMUX_FUNCTION_SEL2
#define PINMUX_T15_I2C3_SCL				PINMUX_FUNCTION_SEL3
#define PINMUX_T15_PRGB_CLK				PINMUX_FUNCTION_SEL5
#define PINMUX_T15_PRGB_B0				PINMUX_FUNCTION_SEL6
#define PINMUX_T15_I2C3_SDA				PINMUX_FUNCTION_SEL8

#ifdef __cplusplus
}
#endif

#endif /* _HC15XX_PINMUX_H_ */
