#ifndef _HC16XX_PINMUX_H_
#define _HC16XX_PINMUX_H_

#ifdef __cplusplus
extern "C" {
#endif

#define PINMUX_FUNCTION_SEL0 0
#define PINMUX_FUNCTION_SEL1 1
#define PINMUX_FUNCTION_SEL2 2
#define PINMUX_FUNCTION_SEL3 3
#define PINMUX_FUNCTION_SEL4 4
#define PINMUX_FUNCTION_SEL5 5
#define PINMUX_FUNCTION_SEL6 6
#define PINMUX_FUNCTION_SEL7 7
#define PINMUX_FUNCTION_SEL8 8
#define PINMUX_FUNCTION_SEL9 9
#define PINMUX_FUNCTION_SELA 10
#define PINMUX_FUNCTION_SELB 11

#define PINMUX_L00_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L00_SPDIF				PINMUX_FUNCTION_SEL1
#define PINMUX_L00_CPU_DIG_PLL_TFCK			PINMUX_FUNCTION_SEL2
#define PINMUX_L00_POK1_OUT33				PINMUX_FUNCTION_SEL3
#define PINMUX_L00_PWM_0				PINMUX_FUNCTION_SEL4
#define PINMUX_L00_RGB_VS				PINMUX_FUNCTION_SEL5
#define PINMUX_L00_VE_DIG_PLL_TFCK			PINMUX_FUNCTION_SEL6
#define PINMUX_L00_CPU1_DIG_PLL_TFCK			PINMUX_FUNCTION_SEL7
#define PINMUX_L00_DE_DIG_PLL_TFCK			PINMUX_FUNCTION_SEL8
#define PINMUX_L00_RGB_HS				PINMUX_FUNCTION_SEL9
#define PINMUX_L00_SPDIF_IN_PAD				PINMUX_FUNCTION_SELA

#define PINMUX_L01_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L01_EJ_TRSTJ				PINMUX_FUNCTION_SEL1
#define PINMUX_L01_I2S_DATAI				PINMUX_FUNCTION_SEL2
#define PINMUX_L01_SSI_MDI0				PINMUX_FUNCTION_SEL3
#define PINMUX_L01_PCMI_DATA				PINMUX_FUNCTION_SEL4
#define PINMUX_L01_PCM0_DATA				PINMUX_FUNCTION_SEL5
#define PINMUX_L01_TDM_DATA				PINMUX_FUNCTION_SEL6
#define PINMUX_L01_PDM0_DATA				PINMUX_FUNCTION_SEL7
#define PINMUX_L01_POK0_OUT11				PINMUX_FUNCTION_SEL8
#define PINMUX_L01_SPI_MOSI				PINMUX_FUNCTION_SELA

#define PINMUX_L02_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L02_EJ_TDI				PINMUX_FUNCTION_SEL1
#define PINMUX_L02_I2S_MCLK				PINMUX_FUNCTION_SEL2
#define PINMUX_L02_SSI_MICLK				PINMUX_FUNCTION_SEL3
#define PINMUX_L02_PCMO_FS				PINMUX_FUNCTION_SEL4
#define PINMUX_L02_PCM0_FS				PINMUX_FUNCTION_SEL5
#define PINMUX_L02_TDM_FS				PINMUX_FUNCTION_SEL6
#define PINMUX_L02_POK0_OUT33				PINMUX_FUNCTION_SEL8
#define PINMUX_L02_SPI_CLK				PINMUX_FUNCTION_SELA

#define PINMUX_L03_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L03_EJ_TDO				PINMUX_FUNCTION_SEL1
#define PINMUX_L03_I2S_LRCK				PINMUX_FUNCTION_SEL2
#define PINMUX_L03_SSI_MIVALA				PINMUX_FUNCTION_SEL3
#define PINMUX_L03_PCMO_BCLK				PINMUX_FUNCTION_SEL4
#define PINMUX_L03_POK1_OUT11				PINMUX_FUNCTION_SEL8
#define PINMUX_L03_SPIM_DCX				PINMUX_FUNCTION_SELA

#define PINMUX_L04_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L04_EJ_TMS				PINMUX_FUNCTION_SEL1
#define PINMUX_L04_I2S_BCLK				PINMUX_FUNCTION_SEL2
#define PINMUX_L04_SSI_MISTART				PINMUX_FUNCTION_SEL3
#define PINMUX_L04_PWM_3				PINMUX_FUNCTION_SEL4
#define PINMUX_L04_PCM0_MCLK				PINMUX_FUNCTION_SEL5
#define PINMUX_L04_SPI_MISO				PINMUX_FUNCTION_SELA

#define PINMUX_L05_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L05_EJ_TCLK				PINMUX_FUNCTION_SEL1
#define PINMUX_L05_I2S_DATAO_0				PINMUX_FUNCTION_SEL2
#define PINMUX_L05_SPDIF				PINMUX_FUNCTION_SEL3
#define PINMUX_L05_PCMO_DATA				PINMUX_FUNCTION_SEL4
#define PINMUX_L05_PCM0_BCLK				PINMUX_FUNCTION_SEL5
#define PINMUX_L05_TDM_BCLK				PINMUX_FUNCTION_SEL6
#define PINMUX_L05_PDM0_CLK				PINMUX_FUNCTION_SEL7
#define PINMUX_L05_PWM_4				PINMUX_FUNCTION_SEL8
#define PINMUX_L05_RGB_VS				PINMUX_FUNCTION_SEL9
#define PINMUX_L05_SPI_CSJ				PINMUX_FUNCTION_SELA

#define PINMUX_L06_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L06_SSI_MDI_0				PINMUX_FUNCTION_SEL1
#define PINMUX_L06_I2C0_SDA				PINMUX_FUNCTION_SEL2
#define PINMUX_L06_I2C1_SDA				PINMUX_FUNCTION_SEL3
#define PINMUX_L06_PWM_2				PINMUX_FUNCTION_SEL4
#define PINMUX_L06_I2S_DATAO_1				PINMUX_FUNCTION_SELA

#define PINMUX_L07_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L07_SSI_MICLK				PINMUX_FUNCTION_SEL1
#define PINMUX_L07_I2C0_SCL				PINMUX_FUNCTION_SEL2
#define PINMUX_L07_I2C1_SCL				PINMUX_FUNCTION_SEL3
#define PINMUX_L07_PWM_3				PINMUX_FUNCTION_SEL4
#define PINMUX_L07_I2S_DATAO_2				PINMUX_FUNCTION_SELA

#define PINMUX_L08_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L08_UART2_TX				PINMUX_FUNCTION_SEL2
#define PINMUX_L08_HRX_OHOT_PLUG_DETECT_A		PINMUX_FUNCTION_SEL3
#define PINMUX_L08_PWM_4				PINMUX_FUNCTION_SEL4
#define PINMUX_L08_HRX_HOT_PULG_IN			PINMUX_FUNCTION_SEL5
#define PINMUX_L08_I2S_DATAO_3				PINMUX_FUNCTION_SELA

#define PINMUX_L09_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L09_SSI_MIVALA				PINMUX_FUNCTION_SEL1
#define PINMUX_L09_UART2_RX				PINMUX_FUNCTION_SEL2
#define PINMUX_L09_HRX_CEC				PINMUX_FUNCTION_SEL3
#define PINMUX_L09_PWM_5				PINMUX_FUNCTION_SEL4
#define PINMUX_L09_I2C3_SDA				PINMUX_FUNCTION_SEL5

#define PINMUX_L10_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L10_SSI_MISTART				PINMUX_FUNCTION_SEL1
#define PINMUX_L10_I2C2_SDA				PINMUX_FUNCTION_SEL2
#define PINMUX_L10_I2C3_SCL				PINMUX_FUNCTION_SEL5
#define PINMUX_L10_PWM_1				PINMUX_FUNCTION_SELA

#define PINMUX_L11_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L11_I2C2_SCL				PINMUX_FUNCTION_SEL2
#define PINMUX_L11_PWM_0				PINMUX_FUNCTION_SEL4

#define PINMUX_L12_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L12_UART0_TX				PINMUX_FUNCTION_SEL1
#define PINMUX_L12_I2C1_SDA				PINMUX_FUNCTION_SEL2
#define PINMUX_L12_HRX_SDA				PINMUX_FUNCTION_SEL3
#define PINMUX_L12_UART3_TX				PINMUX_FUNCTION_SEL4
#define PINMUX_L12_I2C0_SDA				PINMUX_FUNCTION_SEL5
#define PINMUX_L12_RGBHV_H_OUT				PINMUX_FUNCTION_SEL6
#define PINMUX_L12_UART2_TX				PINMUX_FUNCTION_SEL7
#define PINMUX_L12_I2C3_SDA				PINMUX_FUNCTION_SEL8

#define PINMUX_L13_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L13_UART0_RX				PINMUX_FUNCTION_SEL1
#define PINMUX_L13_I2C1_SCL				PINMUX_FUNCTION_SEL2
#define PINMUX_L13_HRX_SCL				PINMUX_FUNCTION_SEL3
#define PINMUX_L13_UART3_RX				PINMUX_FUNCTION_SEL4
#define PINMUX_L13_I2C0_SCL				PINMUX_FUNCTION_SEL5
#define PINMUX_L13_RGBHV_V_OUT				PINMUX_FUNCTION_SEL6
#define PINMUX_L13_UART2_RX				PINMUX_FUNCTION_SEL7
#define PINMUX_L13_I2C3_SCL				PINMUX_FUNCTION_SEL8

#define PINMUX_L14_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L14_IR					PINMUX_FUNCTION_SEL1
#define PINMUX_L14_NF_SMREJ_TST				PINMUX_FUNCTION_SEL2
#define PINMUX_L14_RGB_VS				PINMUX_FUNCTION_SEL3
#define PINMUX_L14_F_CRYSTAL				PINMUX_FUNCTION_SEL4
#define PINMUX_L14_PWM_2				PINMUX_FUNCTION_SEL5
#define PINMUX_L14_POK1_OUT33				PINMUX_FUNCTION_SEL6
#define PINMUX_L14_POK1_OUT11				PINMUX_FUNCTION_SEL7
#define PINMUX_L14_POK0_OUT33				PINMUX_FUNCTION_SEL8
#define PINMUX_L14_POK0_OUT11				PINMUX_FUNCTION_SEL9
#define PINMUX_L14_HDMI_TX_CLK_EXT			PINMUX_FUNCTION_SELA

#define PINMUX_L15_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L15_CEC					PINMUX_FUNCTION_SEL1
#define PINMUX_L15_U0_M_RTSJ				PINMUX_FUNCTION_SEL2
#define PINMUX_L15_I2C0_SDA				PINMUX_FUNCTION_SEL3
#define PINMUX_L15_I2C1_SDA				PINMUX_FUNCTION_SEL4
#define PINMUX_L15_PWM_0				PINMUX_FUNCTION_SEL5
#define PINMUX_L15_RGBHV_H_OUT				PINMUX_FUNCTION_SEL6
#define PINMUX_L15_U2_M_RTSJ				PINMUX_FUNCTION_SEL7
#define PINMUX_L15_HDMI_TMDS_CLK_EXT			PINMUX_FUNCTION_SEL9
#define PINMUX_L15_U1_M_RTSJ				PINMUX_FUNCTION_SELA

#define PINMUX_L16_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L16_HTX_HTPG				PINMUX_FUNCTION_SEL1
#define PINMUX_L16_U0_M_CTSJ				PINMUX_FUNCTION_SEL2
#define PINMUX_L16_I2C0_SCL				PINMUX_FUNCTION_SEL3
#define PINMUX_L16_I2C1_SCL				PINMUX_FUNCTION_SEL4
#define PINMUX_L16_PWM_1				PINMUX_FUNCTION_SEL5
#define PINMUX_L16_RGBHV_V_OUT				PINMUX_FUNCTION_SEL6
#define PINMUX_L16_U2_M_CTSJ				PINMUX_FUNCTION_SEL7
#define PINMUX_L16_HDMI_TX_CLK_EXT			PINMUX_FUNCTION_SEL9
#define PINMUX_L16_U1_M_CTSJ				PINMUX_FUNCTION_SELA

#define PINMUX_L17_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L17_I2C0_SDA				PINMUX_FUNCTION_SEL1
#define PINMUX_L17_UART1_TX				PINMUX_FUNCTION_SEL2
#define PINMUX_L17_UART2_TX				PINMUX_FUNCTION_SEL3
#define PINMUX_L17_HRX_SDA				PINMUX_FUNCTION_SEL4
#define PINMUX_L17_PWM_2				PINMUX_FUNCTION_SEL5
#define PINMUX_L17_UART0_TX				PINMUX_FUNCTION_SEL6
#define PINMUX_L17_I2C3_SDA				PINMUX_FUNCTION_SEL8

#define PINMUX_L18_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L18_I2C0_SCL				PINMUX_FUNCTION_SEL1
#define PINMUX_L18_UART1_RX				PINMUX_FUNCTION_SEL2
#define PINMUX_L18_UART2_RX				PINMUX_FUNCTION_SEL3
#define PINMUX_L18_HRX_SCL				PINMUX_FUNCTION_SEL4
#define PINMUX_L18_PWM_3				PINMUX_FUNCTION_SEL5
#define PINMUX_L18_UART0_RX				PINMUX_FUNCTION_SEL6
#define PINMUX_L18_I2C3_SCL				PINMUX_FUNCTION_SEL8

#define PINMUX_L19_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L19_I2C2_SDA				PINMUX_FUNCTION_SEL1
#define PINMUX_L19_I2C3_SDA				PINMUX_FUNCTION_SEL2
#define PINMUX_L19_UART3_TX				PINMUX_FUNCTION_SEL3
#define PINMUX_L19_HRX_CEC				PINMUX_FUNCTION_SEL4
#define PINMUX_L19_PWM_4				PINMUX_FUNCTION_SEL5

#define PINMUX_L20_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_L20_I2C2_SCL				PINMUX_FUNCTION_SEL1
#define PINMUX_L20_I2C3_SCL				PINMUX_FUNCTION_SEL2
#define PINMUX_L20_UART3_RX				PINMUX_FUNCTION_SEL3
#define PINMUX_L20_HRX_OHOT_PLUG_DETECT_A		PINMUX_FUNCTION_SEL4
#define PINMUX_L20_PWM_5				PINMUX_FUNCTION_SEL5
#define PINMUX_L20_HRX_OHOT_PLUG_IN			PINMUX_FUNCTION_SEL6

#define PINMUX_B00_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B00_RGB_B4				PINMUX_FUNCTION_SEL1
#define PINMUX_B00_I2C1_SCL				PINMUX_FUNCTION_SEL2
#define PINMUX_B00_SSI_MDI_0				PINMUX_FUNCTION_SEL3
#define PINMUX_B00_PWM_0				PINMUX_FUNCTION_SEL5
#define PINMUX_B00_SAR_INT				PINMUX_FUNCTION_SEL8
#define PINMUX_B00_I2S_DATAO_1				PINMUX_FUNCTION_SELA

#define PINMUX_B01_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B01_RGB_B5				PINMUX_FUNCTION_SEL1
#define PINMUX_B01_I2C1_SDA				PINMUX_FUNCTION_SEL2
#define PINMUX_B01_SSI_MICLK				PINMUX_FUNCTION_SEL3
#define PINMUX_B01_PWM_2				PINMUX_FUNCTION_SEL5
#define PINMUX_B01_ADC8B_SW_SEL				PINMUX_FUNCTION_SEL8
#define PINMUX_B01_I2S_DATAO_2				PINMUX_FUNCTION_SELA

#define PINMUX_B02_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B02_RGB_B6				PINMUX_FUNCTION_SEL1
#define PINMUX_B02_I2C2_SCL				PINMUX_FUNCTION_SEL2
#define PINMUX_B02_SSI_MIVALA				PINMUX_FUNCTION_SEL3
#define PINMUX_B02_PWM_1				PINMUX_FUNCTION_SEL5
#define PINMUX_B02_SAR_DOUT_0				PINMUX_FUNCTION_SEL8
#define PINMUX_B02_I2S_DATAO_3				PINMUX_FUNCTION_SELA

#define PINMUX_B03_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B03_RGB_B7				PINMUX_FUNCTION_SEL1
#define PINMUX_B03_I2C2_SDA				PINMUX_FUNCTION_SEL2
#define PINMUX_B03_SSI_MISTART				PINMUX_FUNCTION_SEL3
#define PINMUX_B03_I2S_DATAI				PINMUX_FUNCTION_SEL4
#define PINMUX_B03_PWM_0				PINMUX_FUNCTION_SEL5
#define PINMUX_B03_SAR_DOUT_1				PINMUX_FUNCTION_SEL8

#define PINMUX_B04_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B04_RGB_CLK				PINMUX_FUNCTION_SEL1
#define PINMUX_B04_I2C3_SCL				PINMUX_FUNCTION_SEL2
#define PINMUX_B04_I2S_MCLK				PINMUX_FUNCTION_SEL3
#define PINMUX_B04_RGB_HS				PINMUX_FUNCTION_SEL4
#define PINMUX_B04_PWM_4				PINMUX_FUNCTION_SEL5
#define PINMUX_B04_U0_M_RTSJ				PINMUX_FUNCTION_SEL6
#define PINMUX_B04_U1_M_RTSJ				PINMUX_FUNCTION_SEL7
#define PINMUX_B04_U3_M_RTSJ				PINMUX_FUNCTION_SEL8
#define PINMUX_B04_CEC					PINMUX_FUNCTION_SEL9
#define PINMUX_B04_RGBHV_V_OUT				PINMUX_FUNCTION_SELA

#define PINMUX_B05_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B05_RGB_DE				PINMUX_FUNCTION_SEL1
#define PINMUX_B05_UART1_TX				PINMUX_FUNCTION_SEL2
#define PINMUX_B05_I2S_LRCK				PINMUX_FUNCTION_SEL3
#define PINMUX_B05_PWM_3				PINMUX_FUNCTION_SEL5
#define PINMUX_B05_SAR_DOUT_2				PINMUX_FUNCTION_SEL8

#define PINMUX_B06_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B06_RGB_HS				PINMUX_FUNCTION_SEL1
#define PINMUX_B06_UART1_RX				PINMUX_FUNCTION_SEL2
#define PINMUX_B06_I2S_BCLK				PINMUX_FUNCTION_SEL3
#define PINMUX_B06_PWM_2				PINMUX_FUNCTION_SEL5
#define PINMUX_B06_U0_M_CTSJ				PINMUX_FUNCTION_SEL6
#define PINMUX_B06_U1_M_CTSJ				PINMUX_FUNCTION_SEL7
#define PINMUX_B06_U3_M_CTSJ				PINMUX_FUNCTION_SEL8
#define PINMUX_B06_HTX_HTPG				PINMUX_FUNCTION_SEL9
#define PINMUX_B06_RGBHV_H_OUT				PINMUX_FUNCTION_SELA

#define PINMUX_B07_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B07_RGB_VS				PINMUX_FUNCTION_SEL1
#define PINMUX_B07_I2C3_SDA				PINMUX_FUNCTION_SEL2
#define PINMUX_B07_I2S_DATAO				PINMUX_FUNCTION_SEL3
#define PINMUX_B07_PWM_5				PINMUX_FUNCTION_SEL5
#define PINMUX_B07_SAR_DOUT_3				PINMUX_FUNCTION_SEL8

#define PINMUX_B08_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B08_UART0_TX				PINMUX_FUNCTION_SEL1
#define PINMUX_B08_I2C0_SCL				PINMUX_FUNCTION_SEL2
#define PINMUX_B08_UART3_TX				PINMUX_FUNCTION_SEL3
#define PINMUX_B08_SAR_DOUT_4				PINMUX_FUNCTION_SEL8

#define PINMUX_B09_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B09_UART0_RX				PINMUX_FUNCTION_SEL1
#define PINMUX_B09_I2C0_SDA				PINMUX_FUNCTION_SEL2
#define PINMUX_B09_UART3_RX				PINMUX_FUNCTION_SEL3
#define PINMUX_B09_SAR_DOUT_5				PINMUX_FUNCTION_SEL8

#define PINMUX_B10_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B10_NF_DATA_0				PINMUX_FUNCTION_SEL1
#define PINMUX_B10_I2C3_SCL				PINMUX_FUNCTION_SEL2
#define PINMUX_B10_UART3_TX				PINMUX_FUNCTION_SEL3
#define PINMUX_B10_PWM_0				PINMUX_FUNCTION_SEL5
#define PINMUX_B10_SAR_DOUT_6				PINMUX_FUNCTION_SEL8
#define PINMUX_B10_RGB_HS				PINMUX_FUNCTION_SELA

#define PINMUX_B11_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B11_NF_DATA_1				PINMUX_FUNCTION_SEL1
#define PINMUX_B11_I2C3_SDA				PINMUX_FUNCTION_SEL2
#define PINMUX_B11_UART3_RX				PINMUX_FUNCTION_SEL3
#define PINMUX_B11_PWM_1				PINMUX_FUNCTION_SEL5
#define PINMUX_B11_SAR_DOUT_7				PINMUX_FUNCTION_SEL8
#define PINMUX_B11_RGB_VS				PINMUX_FUNCTION_SELA

#define PINMUX_B12_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B12_NF_DATA_2				PINMUX_FUNCTION_SEL1
#define PINMUX_B12_EJ_TRSTJ				PINMUX_FUNCTION_SEL2
#define PINMUX_B12_I2S_DATAI				PINMUX_FUNCTION_SEL3
#define PINMUX_B12_SSI_MDI_0				PINMUX_FUNCTION_SEL4
#define PINMUX_B12_PCMI_DATA				PINMUX_FUNCTION_SEL5
#define PINMUX_B12_PCM0_DATA				PINMUX_FUNCTION_SEL6
#define PINMUX_B12_TDM_DATA				PINMUX_FUNCTION_SEL7
#define PINMUX_B12_PDM0_DATA				PINMUX_FUNCTION_SEL8
#define PINMUX_B12_NF_SMREJ_TST				PINMUX_FUNCTION_SEL9
#define PINMUX_B12_SPI_MOSI				PINMUX_FUNCTION_SELA

#define PINMUX_B13_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B13_NF_DATA_3				PINMUX_FUNCTION_SEL1
#define PINMUX_B13_EJ_TDI				PINMUX_FUNCTION_SEL2
#define PINMUX_B13_I2S_MCLK				PINMUX_FUNCTION_SEL3
#define PINMUX_B13_SSI_MICLK				PINMUX_FUNCTION_SEL4
#define PINMUX_B13_PCMO_FS				PINMUX_FUNCTION_SEL5
#define PINMUX_B13_PCM0_FS				PINMUX_FUNCTION_SEL6
#define PINMUX_B13_TDM_FS				PINMUX_FUNCTION_SEL7
#define PINMUX_B13_SAR_INT_DOUT_0			PINMUX_FUNCTION_SEL8
#define PINMUX_B13_SPI_CLK				PINMUX_FUNCTION_SELA

#define PINMUX_B14_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B14_NF_DQS				PINMUX_FUNCTION_SEL1
#define PINMUX_B14_PWM_3				PINMUX_FUNCTION_SEL5
#define PINMUX_B14_SAR_INT_DOUT_1			PINMUX_FUNCTION_SEL8

#define PINMUX_B15_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B15_NF_DATA_4				PINMUX_FUNCTION_SEL1
#define PINMUX_B15_EJ_TDO				PINMUX_FUNCTION_SEL2
#define PINMUX_B15_I2S_LRCK				PINMUX_FUNCTION_SEL3
#define PINMUX_B15_SSI_MIVALA				PINMUX_FUNCTION_SEL4
#define PINMUX_B15_PCMO_BCLK				PINMUX_FUNCTION_SEL5
#define PINMUX_B15_I2S_DATAI				PINMUX_FUNCTION_SEL6
#define PINMUX_B15_SAR_INT_DOUT_2			PINMUX_FUNCTION_SEL8
#define PINMUX_B15_SSI_MIERR				PINMUX_FUNCTION_SEL9
#define PINMUX_B15_SPIM_DCX				PINMUX_FUNCTION_SELA

#define PINMUX_B16_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B16_NF_DATA_5				PINMUX_FUNCTION_SEL1
#define PINMUX_B16_EJ_TMS				PINMUX_FUNCTION_SEL2
#define PINMUX_B16_I2S_BCLK				PINMUX_FUNCTION_SEL3
#define PINMUX_B16_SSI_MISTART				PINMUX_FUNCTION_SEL4
#define PINMUX_B16_PWM_4				PINMUX_FUNCTION_SEL5
#define PINMUX_B16_PCM0_MCLK				PINMUX_FUNCTION_SEL6
#define PINMUX_B16_TDM_MCLK				PINMUX_FUNCTION_SEL7
#define PINMUX_B16_SAR_INT_DOUT_3			PINMUX_FUNCTION_SEL8
#define PINMUX_B16_SPI_MISO				PINMUX_FUNCTION_SELA

#define PINMUX_B17_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B17_NF_DATA_6				PINMUX_FUNCTION_SEL1
#define PINMUX_B17_EJ_TCLK				PINMUX_FUNCTION_SEL2
#define PINMUX_B17_I2S_DATAO				PINMUX_FUNCTION_SEL3
#define PINMUX_B17_SPDIF				PINMUX_FUNCTION_SEL4
#define PINMUX_B17_PCMO_DATA				PINMUX_FUNCTION_SEL5
#define PINMUX_B17_PCM0_BCLK				PINMUX_FUNCTION_SEL6
#define PINMUX_B17_TDM_BCLK				PINMUX_FUNCTION_SEL7
#define PINMUX_B17_PDM0_CLK				PINMUX_FUNCTION_SEL8
#define PINMUX_B17_SSI_MIERR				PINMUX_FUNCTION_SEL9
#define PINMUX_B17_SPI_CSJ				PINMUX_FUNCTION_SELA

#define PINMUX_B18_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B18_NF_DATA_7				PINMUX_FUNCTION_SEL1
#define PINMUX_B18_SPIM_DCX				PINMUX_FUNCTION_SEL4
#define PINMUX_B18_PWM_5				PINMUX_FUNCTION_SEL5
#define PINMUX_B18_SAR_INT_DOUT_4			PINMUX_FUNCTION_SEL8
#define PINMUX_B18_IR					PINMUX_FUNCTION_SELA

#define PINMUX_B19_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B19_NF_RDJ				PINMUX_FUNCTION_SEL1
#define PINMUX_B19_I2C2_SCL				PINMUX_FUNCTION_SEL2
#define PINMUX_B19_UART2_TX				PINMUX_FUNCTION_SEL3
#define PINMUX_B19_PCM0_MCLK				PINMUX_FUNCTION_SEL5
#define PINMUX_B19_TDM_MCLK				PINMUX_FUNCTION_SEL6
#define PINMUX_B19_SAR_INT_DOUT_5			PINMUX_FUNCTION_SEL8

#define PINMUX_B20_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B20_NF_CEJ				PINMUX_FUNCTION_SEL1
#define PINMUX_B20_I2C2_SDA				PINMUX_FUNCTION_SEL2
#define PINMUX_B20_UART2_RX				PINMUX_FUNCTION_SEL3
#define PINMUX_B20_SAR_INT_DOUT_6			PINMUX_FUNCTION_SEL8

#define PINMUX_B21_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B21_NF_CLE				PINMUX_FUNCTION_SEL1
#define PINMUX_B21_SSI_MDI_0				PINMUX_FUNCTION_SEL2
#define PINMUX_B21_I2S_DATAO_1				PINMUX_FUNCTION_SEL3
#define PINMUX_B21_I2S2_DATAI				PINMUX_FUNCTION_SEL4
#define PINMUX_B21_PWM_0				PINMUX_FUNCTION_SEL5
#define PINMUX_B21_I2S_MCLK				PINMUX_FUNCTION_SEL6
#define PINMUX_B21_SAR_INT_DOUT_7			PINMUX_FUNCTION_SEL8
#define PINMUX_B21_I2C0_SCL				PINMUX_FUNCTION_SELA

#define PINMUX_B22_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B22_NF_ALE				PINMUX_FUNCTION_SEL1
#define PINMUX_B22_SSI_MICLK				PINMUX_FUNCTION_SEL2
#define PINMUX_B22_I2S_DATAO_2				PINMUX_FUNCTION_SEL3
#define PINMUX_B22_I2S2_MCLK				PINMUX_FUNCTION_SEL4
#define PINMUX_B22_PWM_1				PINMUX_FUNCTION_SEL5
#define PINMUX_B22_I2S_LRCK				PINMUX_FUNCTION_SEL6
#define PINMUX_B22_I2C0_SDA				PINMUX_FUNCTION_SELA

#define PINMUX_B23_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B23_NF_WRJ				PINMUX_FUNCTION_SEL1
#define PINMUX_B23_SSI_MIVALA				PINMUX_FUNCTION_SEL2
#define PINMUX_B23_I2S_DATAO_3				PINMUX_FUNCTION_SEL3
#define PINMUX_B23_I2S2_LRCK				PINMUX_FUNCTION_SEL4
#define PINMUX_B23_PWM_2				PINMUX_FUNCTION_SEL5
#define PINMUX_B23_I2S_BCLK				PINMUX_FUNCTION_SEL6
#define PINMUX_B23_I2C1_SCL				PINMUX_FUNCTION_SELA

#define PINMUX_B24_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_B24_NF_WPJ				PINMUX_FUNCTION_SEL1
#define PINMUX_B24_SSI_MISTART				PINMUX_FUNCTION_SEL3
#define PINMUX_B24_I2S2_BCLK				PINMUX_FUNCTION_SEL4
#define PINMUX_B24_PWM_3				PINMUX_FUNCTION_SEL5
#define PINMUX_B24_I2S_DATAO				PINMUX_FUNCTION_SEL6
#define PINMUX_B24_I2C1_SDA				PINMUX_FUNCTION_SELA

#define PINMUX_R00_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_R00_SF_CSJ1				PINMUX_FUNCTION_SEL1
#define PINMUX_R00_I2C3_SCL				PINMUX_FUNCTION_SEL2
#define PINMUX_R00_I2C1_SCL				PINMUX_FUNCTION_SEL3
#define PINMUX_R00_UART1_TX				PINMUX_FUNCTION_SEL4
#define PINMUX_R00_VIN_D4				PINMUX_FUNCTION_SEL5
#define PINMUX_R00_RMII_MDIO				PINMUX_FUNCTION_SEL6
#define PINMUX_R00_I2S1_DATAI				PINMUX_FUNCTION_SEL7
#define PINMUX_R00_PCM1_FS				PINMUX_FUNCTION_SEL8
#define PINMUX_R00_PDM1_DATAI				PINMUX_FUNCTION_SEL9
#define PINMUX_R00_TDM_MCLK				PINMUX_FUNCTION_SELA

#define PINMUX_R01_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_R01_SF_WJ				PINMUX_FUNCTION_SEL1
#define PINMUX_R01_I2C3_SCL				PINMUX_FUNCTION_SEL2
#define PINMUX_R01_I2C1_SCL				PINMUX_FUNCTION_SEL3
#define PINMUX_R01_UART1_TX				PINMUX_FUNCTION_SEL4
#define PINMUX_R01_VIN_D5				PINMUX_FUNCTION_SEL5
#define PINMUX_R01_RMII_CRS_DV				PINMUX_FUNCTION_SEL6
#define PINMUX_R01_UART2_TX				PINMUX_FUNCTION_SEL7
#define PINMUX_R01_PCM1_BCLK				PINMUX_FUNCTION_SEL8
#define PINMUX_R01_PDM1_CLK				PINMUX_FUNCTION_SEL9
#define PINMUX_R01_I2S_BCLK				PINMUX_FUNCTION_SELA

#define PINMUX_R02_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_R02_SF_CSJ0				PINMUX_FUNCTION_SEL1
#define PINMUX_R02_I2C2_SCL				PINMUX_FUNCTION_SEL3
#define PINMUX_R02_PWM_1				PINMUX_FUNCTION_SEL4
#define PINMUX_R02_VIN_D6				PINMUX_FUNCTION_SEL5
#define PINMUX_R02_RMII_RXD_0				PINMUX_FUNCTION_SEL6
#define PINMUX_R02_I2S1_MCLK				PINMUX_FUNCTION_SEL7
#define PINMUX_R02_PCM2_DATAI				PINMUX_FUNCTION_SEL8
#define PINMUX_R02_TDM_DATAI				PINMUX_FUNCTION_SELA

#define PINMUX_R03_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_R03_SF_MISO				PINMUX_FUNCTION_SEL1
#define PINMUX_R03_PWM_0				PINMUX_FUNCTION_SEL3
#define PINMUX_R03_PCM0_MCLK				PINMUX_FUNCTION_SEL4
#define PINMUX_R03_VIN_D7				PINMUX_FUNCTION_SEL5
#define PINMUX_R03_RMII_RXD_1				PINMUX_FUNCTION_SEL6
#define PINMUX_R03_I2S1_LRCK				PINMUX_FUNCTION_SEL7
#define PINMUX_R03_PCM2_FS				PINMUX_FUNCTION_SEL8
#define PINMUX_R03_PDM2_DATAI				PINMUX_FUNCTION_SEL9
#define PINMUX_R03_TDM_FS				PINMUX_FUNCTION_SELA

#define PINMUX_R04_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_R04_SF_MOSI				PINMUX_FUNCTION_SEL1
#define PINMUX_R04_I2C2_SDA				PINMUX_FUNCTION_SEL3
#define PINMUX_R04_PCM1_MCLK				PINMUX_FUNCTION_SEL4
#define PINMUX_R04_VIN_HS				PINMUX_FUNCTION_SEL5
#define PINMUX_R04_RMII_CLK				PINMUX_FUNCTION_SEL6
#define PINMUX_R04_I2S1_BCLK				PINMUX_FUNCTION_SEL7
#define PINMUX_R04_PCM2_BCLK				PINMUX_FUNCTION_SEL8
#define PINMUX_R04_PDM2_CLK				PINMUX_FUNCTION_SEL9
#define PINMUX_R04_TDM_BCLK				PINMUX_FUNCTION_SELA

#define PINMUX_R05_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_R05_SF_CLK				PINMUX_FUNCTION_SEL1
#define PINMUX_R05_I2C1_SCL				PINMUX_FUNCTION_SEL3
#define PINMUX_R05_VIN_VS				PINMUX_FUNCTION_SEL5
#define PINMUX_R05_PWM_3				PINMUX_FUNCTION_SEL6

#define PINMUX_R06_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_R06_SF_HOLDJ				PINMUX_FUNCTION_SEL1
#define PINMUX_R06_I2C3_SDA				PINMUX_FUNCTION_SEL2
#define PINMUX_R06_I2C1_SDA				PINMUX_FUNCTION_SEL3
#define PINMUX_R06_UART1_RX				PINMUX_FUNCTION_SEL4
#define PINMUX_R06_VIN_CLK				PINMUX_FUNCTION_SEL5
#define PINMUX_R06_PWM_4				PINMUX_FUNCTION_SEL6
#define PINMUX_R06_UART2_RX				PINMUX_FUNCTION_SEL7
#define PINMUX_R06_I2S_DATAO_0				PINMUX_FUNCTION_SELA

#define PINMUX_R07_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_R07_HRX_OHOT_PLUG_IN			PINMUX_FUNCTION_SEL1
#define PINMUX_R07_I2C3_SCL				PINMUX_FUNCTION_SEL2
#define PINMUX_R07_U2_M_RTSJ				PINMUX_FUNCTION_SEL3
#define PINMUX_R07_HRX_OHOT_PLUG_DETECT_A		PINMUX_FUNCTION_SEL4
#define PINMUX_R07_VIN_D2				PINMUX_FUNCTION_SEL5
#define PINMUX_R07_RMII_TXE				PINMUX_FUNCTION_SEL6
#define PINMUX_R07_I2S0_LRCK				PINMUX_FUNCTION_SEL7
#define PINMUX_R07_PCM0_BCLK				PINMUX_FUNCTION_SEL8
#define PINMUX_R07_PCM2_MCLK				PINMUX_FUNCTION_SEL9
#define PINMUX_R07_PWM_2				PINMUX_FUNCTION_SELA

#define PINMUX_R08_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_R08_IR					PINMUX_FUNCTION_SEL1
#define PINMUX_R08_I2C3_SDA				PINMUX_FUNCTION_SEL2
#define PINMUX_R08_U2_M_CTSJ				PINMUX_FUNCTION_SEL3
#define PINMUX_R08_HRX_CEC				PINMUX_FUNCTION_SEL4
#define PINMUX_R08_VIN_D3				PINMUX_FUNCTION_SEL5
#define PINMUX_R08_RMII_MDC				PINMUX_FUNCTION_SEL6
#define PINMUX_R08_I2S0_BCLK				PINMUX_FUNCTION_SEL7
#define PINMUX_R08_PCM1_DATAI				PINMUX_FUNCTION_SEL8
#define PINMUX_R08_PDM0_CLK				PINMUX_FUNCTION_SEL9
#define PINMUX_R08_I2S_LRCK				PINMUX_FUNCTION_SELA
#define PINMUX_R08_PWM_2				PINMUX_FUNCTION_SELB

#define PINMUX_R09_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_R09_UART0_TX				PINMUX_FUNCTION_SEL1
#define PINMUX_R09_I2C1_SCL				PINMUX_FUNCTION_SEL2
#define PINMUX_R09_I2C3_SCL				PINMUX_FUNCTION_SEL3
#define PINMUX_R09_HRX_SCL				PINMUX_FUNCTION_SEL4
#define PINMUX_R09_VIN_D0				PINMUX_FUNCTION_SEL5
#define PINMUX_R09_RMII_TXD_1				PINMUX_FUNCTION_SEL6
#define PINMUX_R09_I2S0_DATAI				PINMUX_FUNCTION_SEL7
#define PINMUX_R09_PCM0_DATAI				PINMUX_FUNCTION_SEL8
#define PINMUX_R09_PDM0_DATAI				PINMUX_FUNCTION_SEL9
#define PINMUX_R09_I2S_DATAI				PINMUX_FUNCTION_SELA

#define PINMUX_R10_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_R10_UART0_RX				PINMUX_FUNCTION_SEL1
#define PINMUX_R10_I2C1_SDA				PINMUX_FUNCTION_SEL2
#define PINMUX_R10_I2C3_SDA				PINMUX_FUNCTION_SEL3
#define PINMUX_R10_HRX_SDA				PINMUX_FUNCTION_SEL4
#define PINMUX_R10_VIN_D1				PINMUX_FUNCTION_SEL5
#define PINMUX_R10_RMII_TXD_0				PINMUX_FUNCTION_SEL6
#define PINMUX_R10_I2S0_MCLK				PINMUX_FUNCTION_SEL7
#define PINMUX_R10_PCM0_FS				PINMUX_FUNCTION_SEL8
#define PINMUX_R10_PCM1_MCLK				PINMUX_FUNCTION_SEL9
#define PINMUX_R10_I2S_MCLK				PINMUX_FUNCTION_SELA

#define PINMUX_T00_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T00_SD_D1				PINMUX_FUNCTION_SEL1
#define PINMUX_T00_SD_PWM1				PINMUX_FUNCTION_SEL4

#define PINMUX_T01_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T01_SD_D0				PINMUX_FUNCTION_SEL1
#define PINMUX_T01_SD_I2C4_SCL			PINMUX_FUNCTION_SEL4

#define PINMUX_T02_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T02_SD_CLK				PINMUX_FUNCTION_SEL1
#define PINMUX_T02_SD_I2C4_SDA			PINMUX_FUNCTION_SEL4

#define PINMUX_T03_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T03_SD_CMD				PINMUX_FUNCTION_SEL1

#define PINMUX_T04_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T04_SD_D3				PINMUX_FUNCTION_SEL1

#define PINMUX_T05_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T05_SD_D2				PINMUX_FUNCTION_SEL1

#define PINMUX_T06_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T06_SD_D4				PINMUX_FUNCTION_SEL1
#define PINMUX_T06_I2C2_SCL				PINMUX_FUNCTION_SEL2
#define PINMUX_T06_I2S_DATAI				PINMUX_FUNCTION_SEL3
#define PINMUX_T06_SSI_MDI1				PINMUX_FUNCTION_SEL4
#define PINMUX_T06_PCMI_DATA				PINMUX_FUNCTION_SEL5
#define PINMUX_T06_PCM0_DATA				PINMUX_FUNCTION_SEL6
#define PINMUX_T06_TDM_DATA				PINMUX_FUNCTION_SEL7
#define PINMUX_T06_PDM0_DATA				PINMUX_FUNCTION_SEL8
#define PINMUX_T06_SSI_ERR				PINMUX_FUNCTION_SELA

#define PINMUX_T07_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T07_SD_D5				PINMUX_FUNCTION_SEL1
#define PINMUX_T07_I2C2_SDA				PINMUX_FUNCTION_SEL2
#define PINMUX_T07_I2S_MCLK				PINMUX_FUNCTION_SEL3
#define PINMUX_T07_SSI_MDI_0				PINMUX_FUNCTION_SEL4
#define PINMUX_T07_PCMO_FS				PINMUX_FUNCTION_SEL5
#define PINMUX_T07_PCM0_FS				PINMUX_FUNCTION_SEL6
#define PINMUX_T07_TDM_FS				PINMUX_FUNCTION_SEL7

#define PINMUX_T08_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T08_SD_D6				PINMUX_FUNCTION_SEL1
#define PINMUX_T08_I2C3_SCL				PINMUX_FUNCTION_SEL2
#define PINMUX_T08_I2S_LRCK				PINMUX_FUNCTION_SEL3
#define PINMUX_T08_SSI_MICLK				PINMUX_FUNCTION_SEL4
#define PINMUX_T08_PCMO_BCLK				PINMUX_FUNCTION_SEL5
#define PINMUX_T08_PCM0_BCLK				PINMUX_FUNCTION_SEL6
#define PINMUX_T08_TDM_BCLK				PINMUX_FUNCTION_SEL7

#define PINMUX_T09_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T09_SD_D7				PINMUX_FUNCTION_SEL1
#define PINMUX_T09_I2C3_SDA				PINMUX_FUNCTION_SEL2
#define PINMUX_T09_I2S_BCLK				PINMUX_FUNCTION_SEL3
#define PINMUX_T09_SSI_MIVALA				PINMUX_FUNCTION_SEL4
#define PINMUX_T09_PWM_1				PINMUX_FUNCTION_SEL5
#define PINMUX_T09_PDM0_CLK				PINMUX_FUNCTION_SEL8

#define PINMUX_T10_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T10_MMC_RST_N				PINMUX_FUNCTION_SEL1
#define PINMUX_T10_I2S_DATAO_0				PINMUX_FUNCTION_SEL3
#define PINMUX_T10_SSI_MISTART				PINMUX_FUNCTION_SEL4
#define PINMUX_T10_PCMO_DATA				PINMUX_FUNCTION_SEL5
#define PINMUX_T10_PWM_5				PINMUX_FUNCTION_SEL7

#define PINMUX_T11_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T11_UART0_TX				PINMUX_FUNCTION_SEL1
#define PINMUX_T11_UART2_TX				PINMUX_FUNCTION_SEL2
#define PINMUX_T11_I2C1_SDA				PINMUX_FUNCTION_SEL4
#define PINMUX_T11_PWM_3				PINMUX_FUNCTION_SEL5

#define PINMUX_T12_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T12_UART0_RX				PINMUX_FUNCTION_SEL1
#define PINMUX_T12_UART2_RX				PINMUX_FUNCTION_SEL2
#define PINMUX_T12_HRX_OHOT_PLUG_DETECT_A		PINMUX_FUNCTION_SEL3
#define PINMUX_T12_I2C1_SCL				PINMUX_FUNCTION_SEL4
#define PINMUX_T12_PWM_2				PINMUX_FUNCTION_SEL5
#define PINMUX_T12_HRX_OHOT_PLUG_IN			PINMUX_FUNCTION_SEL6

#define PINMUX_T13_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T13_SF_CSJ1				PINMUX_FUNCTION_SEL1
#define PINMUX_T13_UART1_TX				PINMUX_FUNCTION_SEL2
#define PINMUX_T13_I2C0_SCL				PINMUX_FUNCTION_SEL3
#define PINMUX_T13_PWM_5				PINMUX_FUNCTION_SEL5
#define PINMUX_T13_I2C3_SCL				PINMUX_FUNCTION_SEL6

#define PINMUX_T14_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T14_SF_WJ				PINMUX_FUNCTION_SEL1
#define PINMUX_T14_UART1_TX				PINMUX_FUNCTION_SEL2
#define PINMUX_T14_I2C0_SCL				PINMUX_FUNCTION_SEL3
#define PINMUX_T14_PWM_5				PINMUX_FUNCTION_SEL5
#define PINMUX_T14_I2C3_SCL				PINMUX_FUNCTION_SEL6
#define PINMUX_T14_PWM_4				PINMUX_FUNCTION_SELA

#define PINMUX_T15_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T15_SF_CSJ0				PINMUX_FUNCTION_SEL1

#define PINMUX_T16_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T16_SF_MISO				PINMUX_FUNCTION_SEL1

#define PINMUX_T17_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T17_SF_MOSI				PINMUX_FUNCTION_SEL1

#define PINMUX_T18_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T18_SF_CLK				PINMUX_FUNCTION_SEL1

#define PINMUX_T19_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T19_SF_HOLDJ				PINMUX_FUNCTION_SEL1
#define PINMUX_T19_UART1_RX				PINMUX_FUNCTION_SEL2
#define PINMUX_T19_I2C0_SDA				PINMUX_FUNCTION_SEL3
#define PINMUX_T19_HRX_OHOT_PLUG_DETECT_A		PINMUX_FUNCTION_SEL4
#define PINMUX_T19_PWM_2				PINMUX_FUNCTION_SEL5
#define PINMUX_T19_I2C3_SDA				PINMUX_FUNCTION_SEL6
#define PINMUX_T19_HRX_OHOT_PLUG_IN			PINMUX_FUNCTION_SEL7
#define PINMUX_T19_HRX_OTMDSCLK				PINMUX_FUNCTION_SEL9

#define PINMUX_T20_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T20_U1_M_RTSJ				PINMUX_FUNCTION_SEL2
#define PINMUX_T20_HRX_OHOT_PLUG_DETECT_A		PINMUX_FUNCTION_SEL3
#define PINMUX_T20_HRX_OHOT_PLUG_IN			PINMUX_FUNCTION_SEL4
#define PINMUX_T20_HRX_OHOT_PLUG_IN			PINMUX_FUNCTION_SEL4
#define PINMUX_T20_PWM_3				PINMUX_FUNCTION_SEL5

#define PINMUX_T21_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T21_HRX_CEC				PINMUX_FUNCTION_SEL1
#define PINMUX_T21_U1_M_CTSJ				PINMUX_FUNCTION_SEL2
#define PINMUX_T21_HRX_OHOT_PLUG_DETECT_A		PINMUX_FUNCTION_SEL3
#define PINMUX_T21_HRX_OHOT_PLUG_IN			PINMUX_FUNCTION_SEL4
#define PINMUX_T21_PWM_4				PINMUX_FUNCTION_SEL5
#define PINMUX_T21_HRX_OTMDSCLK				PINMUX_FUNCTION_SEL9

#define PINMUX_T22_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T22_HRX_SDA				PINMUX_FUNCTION_SEL1
#define PINMUX_T22_I2C0_SDA				PINMUX_FUNCTION_SEL2
#define PINMUX_T22_I2C2_SDA				PINMUX_FUNCTION_SEL3
#define PINMUX_T22_UART0_TX				PINMUX_FUNCTION_SEL4
#define PINMUX_T22_I2C3_SDA				PINMUX_FUNCTION_SEL8
#define PINMUX_T22_USB_DBG_STATUS_0			PINMUX_FUNCTION_SEL9

#define PINMUX_T23_GPIO					PINMUX_FUNCTION_SEL0
#define PINMUX_T23_HRX_SCL				PINMUX_FUNCTION_SEL1
#define PINMUX_T23_I2C0_SCL				PINMUX_FUNCTION_SEL2
#define PINMUX_T23_I2C2_SCL				PINMUX_FUNCTION_SEL3
#define PINMUX_T23_UART0_RX				PINMUX_FUNCTION_SEL4
#define PINMUX_T23_I2C3_SCL				PINMUX_FUNCTION_SEL8
#define PINMUX_T23_USB_DBG_STATUS_1			PINMUX_FUNCTION_SEL9

#ifdef __cplusplus
}
#endif

#endif /* _HC16XX_PINMUX_H_ */
