
elmfat-y = \
	../../third_party/FatFs/source/fs_fat32.o \
	../../third_party/FatFs/source/diskio.o \
	../../third_party/FatFs/source/ff.o \
	../../third_party/FatFs/source/ffsystem.o \
	../../third_party/FatFs/source/ffunicode.o

obj-y += elmfat.o
