CMDS_SUPPORT_SEPARATE_OUTPUT = YES

CMDS_DEPENDENCIES-$(CONFIG_CMDS_PTHREAD) = pthread
CMDS_DEPENDENCIES-$(CONFIG_CMDS_WIFI) = pthread
CMDS_DEPENDENCIES-$(CONFIG_CMDS_HCFOTA) = hcfota

CMDS_DEPENDENCIES = $(CMDS_DEPENDENCIES-y)
CMDS_DEPENDENCIES += kernel

$(eval $(generic-package))

