
#ifndef _STRING_ID_
#define _STRING_ID_

#define STR_QR_CONNECT_AP    1
#define STR_QR_SCAN_WIFI     2
#define STR_QR_CONFIG        3
#define STR_WIFI_SCANNING    4
#define STR_WIFI_CONNECTING  5
#define STR_MIRA_CONNECTING  6
#define STR_MIRA_CONNECT_OK  7
#define STR_AIR_PLAY_MUSIC   8
#define STR_INSERT_ANDROID_OR_APPLE 9
#define STR_REINSERT_ANDROID_OR_APPLE 10
#define STR_PICTURE_MODE     11
#define STR_CONSTRAST        12
#define STR_HUE              13
#define STR_BRIGHTNESS       14
#define STR_COLOR            15
#define STR_SHARPNESS        16
#define STR_COLOR_TEMP       17
#define STR_SOUND_MODE       18
#define STR_TREBLE           19
#define STR_BASS             20
#define STR_BALANCE          21
#define STR_BT_SETTING       22
#define STR_SEARCH_BT        23
#define STR_BT_DEVICE        24
#define STR_BT_MY_DEV        25
#define STR_BT_OTHER_DEV     26
#define STR_NO_BT            27
#define STR_BT_CONN          28
#define STR_BT_DISCONN       29
#define STR_BT_SAVED         30
#define STR_BT_MAKE_DISCONN  31
#define STR_BT_MAKE_CONN     32
#define STR_WIFI_CONNING     33
#define STR_WIFI_SEARCHING   34
#define STR_WIFI_NO_DEVICE   35
#define STR_WIFI_PWD_NULL    36
#define STR_WIFI_CONN_SUCCESS 37
#define STR_WIFI_CONN_FAILED 38
#define STR_WIFI_RE_ENTER_PWD 39
#define STR_PROMPT_YES       40
#define STR_PROMPT_NO        41
#define STR_ENTER_WORD       42
#define STR_WIFI_SSID_NULL   43
#define STR_WIFI_SSID_TOO_LONG 44
#define STR_WIFI_CANCEL      45
#define STR_BT_DELETE        46
#define STR_OSD_LANG_TITLE   47
#define STR_OSD_LANG         48
#define STR_FLIP             49
#define STR_ASPECT_RATIO     50
#define STR_RESTORE_FACTORY_DEFAULT 51
#define STR_UPGRADE          52
#define STR_UPGRADE_NOT_POWER_OFF 53
#define STR_UPGRADE_DOWNLOADING 54
#define STR_UPGRADEING       55
#define STR_AUTO_SLEEP       56
#define STR_OSD_TIMER        57
#define STR_UPGRADE_NO_DEV   58
#define STR_UPGRADE_NO_SOFTWATE 59
#define STR_UPGRADE_LOAD_ERR 60
#define STR_UPGRADE_CRC_ERR  61
#define STR_UPGRADE_VERSION_ERR 62
#define STR_UPGRADE_DECO_ERR 63
#define STR_UPGRADE_ERR      64
#define STR_UPGRADE_SUCCESS_MSG1 65
#define STR_UPGRADE_SUCCESS_MSG2 66
#define STR_KEYSTONE         67
#define STR_VERSION_INFO     68
#define STR_PICTURE_MODE_TITLE 69
#define STR_SOUND_MODE_TITLE 70
#define STR_OPTION_MODE_TITLE 71
#define STR_ADJUST_MODE_TITLE 72
#define STR_FOOT_SURE        73
#define STR_FOOT_MENU        74
#define STR_FOOT_MOVE        75
#define STR_FOOT_OFF         76
#define STR_MOVIE            77
#define STR_MUSIC            78
#define STR_PHOTO            79
#define STR_TEXT             80
#define STR_BACK             81
#define STR_PLAY             82
#define STR_PAUSE            83
#define STR_STOP             84
#define STR_FF               85
#define STR_FB               86
#define STR_NEXT             87
#define STR_PREV             88
#define STR_ROUND            89
#define STR_LISTROUND        90
#define STR_SINGLEROUND      91
#define STR_ZOOMIN           92
#define STR_ZOOMOUT          93
#define STR_ROTATE_LEFT      94
#define STR_ROTATE_RIGHT_K   95
#define STR_NO_EFFECT        96
#define STR_NOR_EFFECT       97
#define STR_SHUTTER_EFFECT   98
#define STR_BRUSH_EFFECT     99
#define STR_SLIDE_EFFECT     100
#define STR_RAND_EFFECT      101
#define STR_FADE_EFFECT      102
#define STR_FILE_FAIL        103
#define STR_AUDIO_USPT       104
#define STR_VIDEO_USPT       105
#define STR_USPT_VIDEO_TYPE  106
#define STR_USPT_AUDIO_TYPE  107
#define STR_AUDIO_ERROR      108
#define STR_VIDEO_ERROR      109
#define STR_PIC_ERROR        110
#define STR_HDMI_TITLE1      111
#define STR_HDMI_TITLE2      112
#define STR_HDMI_TITLE       113
#define STR_MEDIA_TITLE      114
#define STR_AV_TITLE         115
#define STR_HOME_TITLE       116
#define STR_SETTING_TITLE    117
#define STR_HELP_TITLE       118
#define STR_CHANNEL_TITLE    119
#define STR_WIFI_TITLE       120
#define STR_WIRED_TITLE      121
#define STR_WIRELESS_TITLE   122
#define STR_OFF              123
#define STR_ON               124
#define STR_STANDARD         125
#define STR_DYNAMIC          126
#define STR_MILD             127
#define STR_USER             128
#define STR_COLD             129
#define STR_WARM             130
#define STR_SPORTS           131
#define STR_ENGLISH          132
#define STR_CHINESE          133
#define STR_FRONT_TABLE      134
#define STR_FRONT_CEILING    135
#define STR_BACK_TABLE       136
#define STR_BACK_CEILING     137
#define STR_RESTORE_OK_1     138
#define STR_RESTORE_OK_2     139
#define STR_RESTORE_CLOSE    140
#define STR_OSD_TIME_5S      141
#define STR_OSD_TIEM_10S     142
#define STR_OSD_TIME_15S     143
#define STR_OSD_TIME_20S     144
#define STR_OSD_TIME_25S     145
#define STR_OSD_TIME_30S     146
#define STR_AUTO_SLEEP_1H    147
#define STR_AUTO_SLEEP_2H    148
#define STR_AUTO_SLEEP_3H    149
#define STR_INPUT_SOURCE     150
#define STR_VOLUME           151
#define STR_LIST             152
#define STR_INFO             153
#define STR_SF               154
#define STR_STEP             155
#define STR_INFO_RES         156
#define STR_INFO_FRAME       157
#define STR_INFO_AUDIO       158
#define STR_INFO_SUBTITLE    159
#define STR_INFO_SIZE        160
#define STR_INFO_ALBUM       161
#define STR_INFO_ARTIST      162
#define STR_INFO_BIT         163
#define STR_INFO_EXIT        164
#define STR_PANEL_CLOSE      165
#define STR_MUTE             166
#define STR_MUSIC_OFF        167
#define STR_MUSIC_ON         168
#define STR_MUSIC_SRC        169
#define STR_FILE_DATE        170
#define STR_FILE_TIME        171
#define STR_SETUP            172
#define STR_ASPECT_AUTO      173
#define STR_ASPECT_4_3       174
#define STR_ASPECT_16_9      175
#define STR_USB_MOUNT_FAIL_MSG 176
#define STR_NETWORK_ERR      177
#define STR_CONNECT_WIFI_FAIL 178
#define STR_CONNECT_WIFI_FIRST 179
#define STR_VIDEO_DATA_ERR   180
#define STR_AUDIO_DATA_ERR   181
#define STR_VIDEO_FORMAT_NOT_SUPPORT 182
#define STR_AUDIO_FORMAT_NOT_SUPPORT 183
#define STR_WIFI_DISCONNECT  184
#define STR_MEDIA_CONTAINER_NOT_SUPPORT 185
#define STR_WIFI_SAVED       186
#define STR_WIFI_NEARBY      187
#define STR_WIFI_SEARCH      188
#define STR_WIFI_ADD         189
#define STR_WIFI_RET         190
#define STR_WIFI_STRENGTH    191
#define STR_WIFI_SECURITY    192
#define STR_WIFI_PWD         193
#define STR_WIFI_SHOW_PWD    194
#define STR_WIFI_NET_MODE    195
#define STR_WIFI_IP_ADDR     196
#define STR_WIFI_NET_MASK    197
#define STR_WIFI_GATE_WAY    198
#define STR_WIFI_DNS         199
#define STR_WIFI_MAC         200
#define STR_WIFI_STATIC_IP   201
#define STR_WIFI_CONNECT_ERR 202
#define STR_WIFI_NOT_CONNECT 203
#define STR_RESET            204
#define STR_FOCUS_FORWAD     205
#define STR_FOCUS_BACK       206
#define STR_FOCUS            207
#define STR_EBOOK_UP         208
#define STR_EBOOK_DOWN       209
#define STR_EBOOK_PREV       210
#define STR_EBOOK_NEXT       211
#define STR_SUBTITLE_MSG     212
#define STR_ZOOMMOVE         213
#define STR_MP_NO_DEV        214
#define STR_MIRROR_ROTATE_ON 215
#define STR_MIRROR_ROTATE_OFF 216
#define STR_FRENCH           217
#define STR_LANG             218
#define STR_ENTER_STANDBY    219
#define STR_WINDOW_SCALE     220
#define STR_WIFI_READY       221
#define STR_ANDROID_SCAN_QR  222
#define STR_USB_UPG_READ     223
#define STR_NET_UPG_DOWNLOAD 224
#define STR_USB_UPG_OPEN_FILE_FAIL 225
#define STR_USB_UPG_FILE_LARGE 226
#define STR_USB_UPG_READ_FAIL 227
#define STR_NET_UPG_HTTP_BAD 228
#define STR_UPG_USER_CANCEL  229
#define STR_UPG_PRODUCT_ID_MISMATCH 230
#define STR_UPG_SW_VER_NOT_UPG 231
#define STR_UPG_SW_ILLGAL    232
#define STR_UPG_UNZIP_FAIL   233
#define STR_UPG_BURNING      234
#define STR_USB_UPG_OK       235
#define STR_NET_UPG_OK       236
#define STR_UPG_BURN_FAIL    237
#define STR_BT_DISCONNECTED  238
#define STR_BT_CONNECTED     239
#define STR_BT_CONN_FAILED   240
#define STR_HDMI_FORMAT_USPT 241
#define STR_NO_SIGNAL        242

#endif//_STRING_ID_
