#ifndef _HCUAPI_AVEVENT_H_
#define _HCUAPI_AVEVENT_H_

#include <hcuapi/iocbase.h>

#define AVEVENT_AUDDEC_FATAL_ERR		_IO  (AVEVENT_IOCBASE,   0)

#define AVEVENT_VIDDEC_FATAL_ERR		_IO  (AVEVENT_IOCBASE,  50)
#define AVEVENT_VIDDEC_RESOLUTION_ERR		_IO  (AVEVENT_IOCBASE,  51)

#define AVEVENT_VIDDEC_FIRST_FRAME_DECODED	_IO  (AVEVENT_IOCBASE,  100)
#define AVEVENT_VIDDEC_FIRST_FRAME_SHOWED	_IO  (AVEVENT_IOCBASE,  101)

#define AVEVENT_VIDDEC_FRAME_DE_SHOWED		_IO  (AVEVENT_IOCBASE,  102)
#define AVEVENT_VIDDEC_FRAME_DECODED		_IO  (AVEVENT_IOCBASE,  103)
#define AVEVENT_VIDDEC_FIRST_FRAME_TRANSCODED	_IO  (AVEVENT_IOCBASE,  104)

#endif /* _HCUAPI_AVEVENT_H_ */
