#ifndef _HCUAPI_IOCBASE_H_
#define _HCUAPI_IOCBASE_H_

#include <asm/ioctls.h>

#define VIRTUART_IOCBASE		(1)
#define AVSYNC_IOCBASE			(2)
#define AUDIO_IOCBASE			(3)
#define VIDEO_IOCBASE			(4)
#define KSHM_IOCBASE			(5)
#define RAMDISK_IOCBASE 		(6)
#define SCI_IOCBASE 			(7)
#define SND_IOCBASE 			(8)
#define AUDSINK_IOCBASE			(9)
#define HDMI_RX_IOCBASE			(10)
#define AVEVENT_IOCBASE			(11)
#define KUMSGQ_IOCBASE			(12)
#define HCFB_IOCBASE			(13)
#define DIS_IOCBASE			(14)
#define INPUT_IOCBASE			(15)
#define MTD_IOCBASE			(16)
#define SPI_IOCBASE			(17)
#define I2C_IOCBASE			(18)
#define LVDS_IOCBASE			(19)
#define DUMPSTACK_IOCBASE		(20)
#define AVCOMMON_IOCBASE		(21)
#define WATCHDOG_IOCBASE		(22)
#define PWM_IOCBASE			(23)
#define DSC_IOCBASE			(24)
#define MMZ_IOCBASE			(25)
#define VIDSINK_IOCBASE			(26)
#define TVDEC_IOCBASE			(27)
#define HDMI_TX_IOCBASE			(28)
#define VINDVP_IOCBASE			(29)
#define MIPI_IOCBASE			(30)
#define EFUSE_IOCBASE			(31)
#define POK_IOCBASE			(32)
#define SARADC_IOCBASE			(33)
#define USBDEVFS_IOCBASE		(34)
#define HCGE_IOCBASE			(35)
#define SDMMC_IOCBASE			(36)
#define PQ_IOCBASE			(37)
#define PERSISTENTMEM_IOCBASE		(38)
#define STANDBY_IOCBASE			(39)
#define DVPDEVIDE_IOCBASE		(40)
#define USBHID_IOCBASE			(41)

#endif /* _HCUAPI_IOCBASE_H_ */
