pipes-y = \
	../../third_party/nuttx/drivers/pipes/fifo.o \
	../../third_party/nuttx/drivers/pipes/pipe_common.o \
	../../third_party/nuttx/drivers/pipes/pipe.o \
	../../third_party/nuttx/drivers/pipes/pipe_dump.o 

obj-y += pipes.o
