cflags-$(BR2_PACKAGE_PREBUILTS_3A) += -DCMD_BR2_PACKAGE_PREBUILTS_3A

sound_test-y += sound_test.o i2so_test.o \
	i2si_test.o tdmi_test.o \
	spin_test.o pdmi_test.o \
	pcmi_test.o  i2si012_test.o \
	i2si_i2so_recoder_test.o \
	pcm_rec_play.o i2s_rec_play.o \
	spectrum_test.o aec_test.o \
	aec_main.o alac_dec.o \
	dsp_test.o

obj-y += sound_test.o