obj-$(CONFIG_VFS) += vfs/
obj-$(CONFIG_FS_ELMFAT) += elmfat/
obj-$(CONFIG_FS_ROMFS) += romfs/
obj-$(CONFIG_MMAP) += mmap/
obj-$(CONFIG_PARTITION) += partition/
obj-$(CONFIG_FS_AUTOMOUNTER) += mount/
obj-$(CONFIG_FS_LITTLEFS) += littlefs/
obj-$(CONFIG_FS_YAFFS2) += yaffs2/
