cflags-y += -Wno-sign-compare -Wno-format-truncation -Wno-implicit-fallthrough
cflags-y	+= -I$(src) -Wno-implicit-fallthrough -Wno-int-conversion -Wno-sign-compare -Wno-error=format=
cflags-y	+= -I$(src)/

obj-y += function/ legacy/
