obj-$(CONFIG_LIB_CONSOLE) += console/
obj-$(CONFIG_LIB_ELOG) += easylogger/
obj-$(CONFIG_LIB_FDT) += fdt/
obj-$(CONFIG_LIB_CRC) += crc/
obj-$(CONFIG_LIB_LZMA) += lzma/
obj-$(CONFIG_LIB_GZIP) += zlib/
obj-y += libc/
