#ifndef __HCCAST_HTTPD_SERVICE_H__
#define __HCCAST_HTTPD_SERVICE_H__
int hccast_httpd_service_start(void);
int hccast_httpd_service_stop(void);
int hccast_httpd_service_is_start(void);

typedef enum 
{
	HCCAST_HTTPD_NONE = 0,
	HCCAST_HTTPD_GET_DEV_INFO,
	HCCAST_HTTPD_DEVICE_UPG,
	HCCAST_HTTPD_DELETE_WIFI_INFO,
	HCCAST_HTTPD_WIFI_AP_DISCONNECT,
	HCCAST_HTTPD_WIFI_AP_CONNECT,
	HCCAST_HTTPD_CHECK_AP_SAVE,
	HCCAST_HTTPD_GET_DEVICE_NAME,
	HCCAST_HTTPD_SET_DEVICE_NAME,
	HCCAST_HTTPD_GET_DEVICE_PSK,
	HCCAST_HTTPD_SET_DEVICE_PSK,
	HCCAST_HTTPD_GET_DEVICE_MAC,
	HCCAST_HTTPD_GET_SYS_BRIGHT,
	HCCAST_HTTPD_SET_SYS_BRIGHT,
	HCCAST_HTTPD_GET_SYS_CONTRAST,
	HCCAST_HTTPD_SET_SYS_CONTRAST,
	HCCAST_HTTPD_GET_SYS_SATURATION,
	HCCAST_HTTPD_SET_SYS_SATURATION,
	HCCAST_HTTPD_GET_SYS_HUE,
	HCCAST_HTTPD_SET_SYS_HUE,
	HCCAST_HTTPD_GET_SYS_SHARPNESS,
	HCCAST_HTTPD_SET_SYS_SHARPNESS,
	HCCAST_HTTPD_GET_SYS_RESOLUTION,
	HCCAST_HTTPD_SET_SYS_RESOLUTION,
	HCCAST_HTTPD_GET_BROWSER_LANGUAGE,
	HCCAST_HTTPD_SET_BROWSER_LANGUAGE,
	HCCAST_HTTPD_GET_RATIO_DISPLAY_MODE,
	HCCAST_HTTPD_SET_RATIO_DISPLAY_MODE,
	HCCAST_HTTPD_GET_AIRCAST_MODE,
	HCCAST_HTTPD_SET_AIRCAST_MODE,
	HCCAST_HTTPD_GET_MIRROR_FRAME,
	HCCAST_HTTPD_SET_MIRROR_FRAME,
	HCCAST_HTTPD_GET_MIRROR_MODE,
	HCCAST_HTTPD_SET_MIRROR_MODE,
	HCCAST_HTTPD_SET_SYS_RESTART,
	HCCAST_HTTPD_SET_SYS_RESET,
	HCCAST_HTTPD_GET_CUR_WIFI_INFO,
	HCCAST_HTTPD_SHOW_PROGRESS,
	HCCAST_HTTPD_GET_UPGRADE_FILE_BEGING,
	HCCAST_HTTPD_MSG_UPGRADE_BAD_RES,
	HCCAST_HTTPD_MSG_USER_UPGRADE_ABORT,
	HCCAST_HTTPD_MSG_UPGRADE_FILE_SUC,
	HCCAST_HTTPD_GET_UPLOAD_DATA_START,
	HCCAST_HTTPD_GET_UPLOAD_DATA_FAILED,
	HCCAST_HTTPD_MSG_UPLOAD_DATA_SUC,
	HCCAST_HTTPD_GET_DEV_PRODUCT_ID,
	HCCAST_HTTPD_GET_DEV_VERSION,
	HCCAST_HTTPD_GET_WIFI_FREQ_MODE_EN,
	HCCAST_HTTPD_GET_WIFI_FREQ_MODE,
	HCCAST_HTTPD_SET_WIFI_FREQ_MODE,
	HCCAST_HTTPD_GET_CUR_SCENE_PLAY,
	HCCAST_HTTPD_STOP_MIRA_SERVICE,
	HCCAST_HTTPD_START_MIRA_SERVICE,
	HCCAST_HTTPD_MSG_UPGRADE_SERVER_BAD,
	HCCAST_HTTPD_GET_MIRROR_ROTATION,
	HCCAST_HTTPD_SET_MIRROR_ROTATION,
	HCCAST_HTTPD_GET_WIFI_CONNECT_STATUS,
	HCCAST_HTTPD_GET_CUR_WIFI_SSID,
	HCCAST_HTTPD_WIFI_SCAN,
	HCCAST_HTTPD_GET_NOT_SUPPORT_4K,
	HCCAST_HTTPD_GET_WIFI_HS_CHANNEL,
	HCCAST_HTTPD_SET_WIFI_HS_CHANNEL,
	HCCAST_HTTPD_WIFI_STAT_CHECK_BUSY,
	HCCAST_HTTPD_GET_WIFI_HS_CHANNEL_BY_FREQ_MODE,
	HCCAST_HTTPD_GET_MIRROR_VSCREEN_AUTO_ROTATION,
	HCCAST_HTTPD_SET_MIRROR_VSCREEN_AUTO_ROTATION,
	HCCAST_HTTPD_WIFI_SWITCH,
	HCCAST_HTTPD_GET_UPGRADE_URL,
	HCCAST_HTTPD_MAX,
} hccast_httpd_event_e;

typedef int (*hccast_httpd_callback) (hccast_httpd_event_e event, void* in, void* out);

#define SERVICE_NAME_MAX_LEN 32
#define DEVICE_PSK_MAX_LEN 16
#define HTTP_UPG_SERVER_MAX_LEN 128
#define WIFI_AP_MAX_NUM 5

typedef struct
{
    char *buf;
    unsigned int length;
} hccast_web_upload_info_st;

typedef struct
{
    char *buf;
    unsigned int length;
} hccast_web_upgrade_info_st;

#ifdef __cplusplus
extern "C" {
#endif

int hccast_httpd_service_init(hccast_httpd_callback func);
int hccast_httpd_service_uninit(void);

#ifdef __cplusplus
}
#endif

#endif
