KERNEL_SUPPORT_SEPARATE_OUTPUT = YES

KERNEL_DEPENDENCIES += newlib
KERNEL_DEPENDENCIES-$(CONFIG_CUSTOM_DTS) += host-dtc
KERNEL_DEPENDENCIES-$(CONFIG_LIB_GZIP) += zlib
KERNEL_DEPENDENCIES += $(KERNEL_DEPENDENCIES-y)

$(eval $(generic-package))
