cflags-y += -Wno-int-conversion
cflags-y += -Wno-error=format= -Wno-unused-variable

spi-nor-y :=  core.o sfdp.o

spi-nor-y +=  atmel.o
spi-nor-y +=  catalyst.o
spi-nor-y +=  eon.o
spi-nor-y +=  esmt.o
spi-nor-y +=  everspin.o
spi-nor-y +=  fujitsu.o
spi-nor-y +=  gigadevice.o
spi-nor-y +=  intel.o
spi-nor-y +=  issi.o
spi-nor-y +=  macronix.o
spi-nor-y +=  micron-st.o
spi-nor-y +=  spansion.o
spi-nor-y +=  sst.o
spi-nor-y +=  winbond.o
spi-nor-y +=  xilinx.o
spi-nor-y +=  xmc.o
spi-nor-y +=  general.o

obj-y += spi-nor.o
