aplatform-y := wm8960-dai.o i2so_platform_reg.o \
	pcmo_platform_reg.o \
	i2si_platform_reg.o pcmi_platform_reg.o \
	tdmi_platform_reg.o \
	pdmi0_platform_reg.o wm8960i-dai.o \
	cs4344-dai.o \
	i2si0_platform_reg.o i2si1_platform_reg.o \
	i2si2_platform_reg.o pcmi0_platform_reg.o \
	pcmi1_platform_reg.o pcmi2_platform_reg.o \
	wm8960-for-i2si-dai.o \
	cjc8990-dai.o cjc8988-dai.o

obj-y += aplatform.o
