keymaps-y := rc-hcdemo.o

obj-$(CONFIG_RC_KEYMAP_HCDEMO) += keymaps.o

rc-projector-y := rc-projector-c1.o

obj-$(CONFIG_RC_KEYMAP_PROJECTOR_C1) += rc-projector.o

projector-c1-wjv6-y := rc-projector-c1-wjv6.o

obj-$(CONFIG_RC_KEYMAP_PROJECTOR_C1_WJV6) += projector-c1-wjv6.o

projector-c1-ak02-y := rc-projector-c1-ak02.o
obj-$(CONFIG_RC_KEYMAP_PROJECTOR_C1_AK02) += projector-c1-ak02.o

projector-c2-y := rc-projector-c2.o
obj-$(CONFIG_RC_KEYMAP_PROJECTOR_C2_D3000) += projector-c2.o
